### ISSUE TITLE
Error response from daemon: invalid volume specification

### ISSUE THREAD

**Issue by Legends** [TimCorey/getting-started-with-docker#1]
Just followed your tutorial "sample 3".
Dev cert is created in `C:\temp\docker\`.
But I get the below error:

> C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: invalid volume specification: 'C:\temp\docker\:/root/.dotnet/https'.

`docker run -d -p 8000:80 -p 8443:443 -e ASPNETCORE_HTTPS_PORT=8443 -e ASPNETCORE_URLS="https://+:443;http://+:80" -e Kestrel__Certificates__Default__Path=/root/.dotnet/https/cert-aspnetcore.pfx -e Kestrel__Certificates__Default__Password=mypwd-v C:\temp\docker\:/root/.dotnet/https --name=second_attempt webapp:1.0.0`

**Comment by TimCorey** [comment]
The error message does not list the trailing slash after docker but your script shows a trailing slash. Did you verify that you included that trailing slash when you ran your command?

**Comment by Legends** [comment]
The script is a copy of my console command, yes the trailing slash is there, it does not show up in the error msg though.

I am running  on: ` Win Enterprise 10.0.18363 N/A Build 18363`

**Comment by Legends** [comment]
Do I have to switch to Linux Containers? Because the image is a Linux image, right?

![image](https://user-images.githubusercontent.com/966368/79916196-9a451b80-8428-11ea-827f-7572f6f5c466.png)

**Comment by Legends** [comment]
That was the issue... my first steps with Docker ;-)
